name = mcl_furnaces
description = rewrite of mtg/mcl2 furnace code to not wake up every damn second
author = cora
depends = mcl_init, mcl_formspec, mcl_sounds, mcl_craftguide, mcl_achievements, mcl_util
