NS("Yellow Bed")
NS("Lime Bed")
NS("Grey Bed")
NS("White Bed")
NS("Red Bed")
NS("Magenta Bed")
NS("Blue Bed")
NS("Light Blue Bed")
NS("Light Grey Bed")
NS("Black Bed")
NS("Green Bed")
NS("Pink Bed")
NS("Cyan Bed")
NS("Brown Bed")
NS("Orange Bed")
NS("Purple Bed")
