name = mobs_mc_bones_workaround
depends = mobs_mc
description = workaround for an inconsitency in bone overrides between luanti 5.11 and prior versions. This mod can entirely be removed when support for luanti <5.11 is dropped
