NS("Yellow Wool")
NS("Yellow Carpet")
NS("Lime Wool")
NS("Lime Carpet")
NS("Grey Wool")
NS("Grey Carpet")
NS("White Wool")
NS("White Carpet")
NS("Red Wool")
NS("Red Carpet")
NS("Magenta Wool")
NS("Magenta Carpet")
NS("Blue Wool")
NS("Blue Carpet")
NS("Light Blue Wool")
NS("Light Blue Carpet")
NS("Light Grey Wool")
NS("Light Grey Carpet")
NS("Black Wool")
NS("Black Carpet")
NS("Green Wool")
NS("Green Carpet")
NS("Pink Wool")
NS("Pink Carpet")
NS("Cyan Wool")
NS("Cyan Carpet")
NS("Brown Wool")
NS("Brown Carpet")
NS("Orange Wool")
NS("Orange Carpet")
NS("Purple Wool")
NS("Purple Carpet")
