NS("Yellow Concrete Stairs")
NS("Yellow Concrete Slab")
NS("Yellow Terracotta Stairs")
NS("Yellow Terracotta Slab")
NS("Lime Concrete Stairs")
NS("Lime Concrete Slab")
NS("Lime Terracotta Stairs")
NS("Lime Terracotta Slab")
NS("Grey Concrete Stairs")
NS("Grey Concrete Slab")
NS("Grey Terracotta Stairs")
NS("Grey Terracotta Slab")
NS("White Concrete Stairs")
NS("White Concrete Slab")
NS("White Terracotta Stairs")
NS("White Terracotta Slab")
NS("Red Concrete Stairs")
NS("Red Concrete Slab")
NS("Red Terracotta Stairs")
NS("Red Terracotta Slab")
NS("Magenta Concrete Stairs")
NS("Magenta Concrete Slab")
NS("Magenta Terracotta Stairs")
NS("Magenta Terracotta Slab")
NS("Blue Concrete Stairs")
NS("Blue Concrete Slab")
NS("Blue Terracotta Stairs")
NS("Blue Terracotta Slab")
NS("Light Blue Concrete Stairs")
NS("Light Blue Concrete Slab")
NS("Light Blue Terracotta Stairs")
NS("Light Blue Terracotta Slab")
NS("Light Grey Concrete Stairs")
NS("Light Grey Concrete Slab")
NS("Light Grey Terracotta Stairs")
NS("Light Grey Terracotta Slab")
NS("Black Concrete Stairs")
NS("Black Concrete Slab")
NS("Black Terracotta Stairs")
NS("Black Terracotta Slab")
NS("Green Concrete Stairs")
NS("Green Concrete Slab")
NS("Green Terracotta Stairs")
NS("Green Terracotta Slab")
NS("Pink Concrete Stairs")
NS("Pink Concrete Slab")
NS("Pink Terracotta Stairs")
NS("Pink Terracotta Slab")
NS("Cyan Concrete Stairs")
NS("Cyan Concrete Slab")
NS("Cyan Terracotta Stairs")
NS("Cyan Terracotta Slab")
NS("Brown Concrete Stairs")
NS("Brown Concrete Slab")
NS("Brown Terracotta Stairs")
NS("Brown Terracotta Slab")
NS("Orange Concrete Stairs")
NS("Orange Concrete Slab")
NS("Orange Terracotta Stairs")
NS("Orange Terracotta Slab")
NS("Purple Concrete Stairs")
NS("Purple Concrete Slab")
NS("Purple Terracotta Stairs")
NS("Purple Terracotta Slab")
