name = mcl_charges
description = Adds Code to easily register throwable charges like the wind charge
depends = mcl_tnt, mcl_sounds, mcl_mobitems, mcl_mobs
optional_depends = mobs_mc
title = MCL Charges