NS("Yellow Dye")
NS("Lime Dye")
NS("Grey Dye")
NS("White Dye")
NS("Red Dye")
NS("Magenta Dye")
NS("Blue Dye")
NS("Light Blue Dye")
NS("Light Grey Dye")
NS("Black Dye")
NS("Green Dye")
NS("Pink Dye")
NS("Cyan Dye")
NS("Brown Dye")
NS("Orange Dye")
NS("Purple Dye")
