local S = minetest.get_translator(minetest.get_current_modname())
return {
	concrete = {
		white = S("White Concrete"),
		silver = S("Light Grey Concrete"),
		grey = S("Grey Concrete"),
		black = S("Black Concrete"),
		purple = S("Purple Concrete"),
		blue = S("Blue Concrete"),
		light_blue = S("Light Blue Concrete"),
		cyan = S("Cyan Concrete"),
		green = S("Green Concrete"),
		lime = S("Lime Concrete"),
		yellow = S("Yellow Concrete"),
		brown = S("Brown Concrete"),
		orange = S("Orange Concrete"),
		red = S("Red Concrete"),
		magenta = S("Magenta Concrete"),
		pink = S("Pink Concrete"),
	},
	concrete_powder = {
		white = S("White Concrete Powder"),
		silver = S("Light Grey Concrete Powder"),
		grey = S("Grey Concrete Powder"),
		black = S("Black Concrete Powder"),
		purple = S("Purple Concrete Powder"),
		blue = S("Blue Concrete Powder"),
		light_blue = S("Light Blue Concrete Powder"),
		cyan = S("Cyan Concrete Powder"),
		green = S("Green Concrete Powder"),
		lime = S("Lime Concrete Powder"),
		yellow = S("Yellow Concrete Powder"),
		brown = S("Brown Concrete Powder"),
		orange = S("Orange Concrete Powder"),
		red = S("Red Concrete Powder"),
		magenta = S("Magenta Concrete Powder"),
		pink = S("Pink Concrete Powder"),
	},
	terracotta = {
		white = S("White Terracotta"),
		silver = S("Light Grey Terracotta"),
		grey = S("Grey Terracotta"),
		black = S("Black Terracotta"),
		purple = S("Purple Terracotta"),
		blue = S("Blue Terracotta"),
		light_blue = S("Light Blue Terracotta"),
		cyan = S("Cyan Terracotta"),
		green = S("Green Terracotta"),
		lime = S("Lime Terracotta"),
		yellow = S("Yellow Terracotta"),
		brown = S("Brown Terracotta"),
		orange = S("Orange Terracotta"),
		red = S("Red Terracotta"),
		magenta = S("Magenta Terracotta"),
		pink = S("Pink Terracotta"),
	},
	glazed_terracotta = {
		white = S("White Glazed Terracotta"),
		silver = S("Light Grey Glazed Terracotta"),
		grey = S("Grey Glazed Terracotta"),
		black = S("Black Glazed Terracotta"),
		purple = S("Purple Glazed Terracotta"),
		blue = S("Blue Glazed Terracotta"),
		light_blue = S("Light Blue Glazed Terracotta"),
		cyan = S("Cyan Glazed Terracotta"),
		green = S("Green Glazed Terracotta"),
		lime = S("Lime Glazed Terracotta"),
		yellow = S("Yellow Glazed Terracotta"),
		brown = S("Brown Glazed Terracotta"),
		orange = S("Orange Glazed Terracotta"),
		red = S("Red Glazed Terracotta"),
		magenta = S("Magenta Glazed Terracotta"),
		pink = S("Pink Glazed Terracotta"),
	}
}

