------------------------------------------------------------------------
-- Biome generation.
------------------------------------------------------------------------

-- Number of quart positions per MapBlock.
local N = 4

local function index (x, y, z, dx, dy, dz)
	return x * dy * dz + y * dx + z + 1
end

if not core or core.save_gen_notify then -- Mapgen environment.

-- Return biomes in the table BIOMES for each position in the region
-- from X, Y, Z to X1, Y1, Z1, in PRESET, which must be Minecraft
-- block positions divided by 4.  The index of each position so
-- divided in this table is produced from the difference between each
-- such position and the supplied origin in X-major, Z-minor order.

function mcl_levelgen.generate_biomes (preset, biomes, x, y, z, x1, y1, z1)
	local dx = x1 - x + 1
	local dy = y1 - y + 1
	local dz = z1 - z + 1
	for xpos = x, x1 do
		for ypos = y, y1 do
			for zpos = z, z1 do
				local biome = preset:index_biomes (xpos, ypos, zpos)
				local idx = index (xpos - x, ypos - y, zpos - z,
						   dx, dy, dz)
				biomes[idx] = biome
			end
		end
	end
end

-- Likewise, but for a column of Minetest MapBlocks of dimensions W
-- and H at X, Y, Z (i.e., Minecraft X, Y, -Z - (W - 1) - 1).

function mcl_levelgen.generate_biomes_at_block (preset, biomes, x, y, z, w, h)
	local qx, qy, qz = x * N, y * N, z * N
	local qw, qh = w * N, h * N
	local qx2, qy2, qz2 = qx + qw - 1, qy + qh - 1, qz + qw - 1
	mcl_levelgen.generate_biomes (preset, biomes, qx, qy, -qz2 - 1,
				      qx2, qy2, -qz - 1)
end

-- Generate a run-length encoding indexed by MapBlock of a table of
-- biomes TABLE generated by mcl_levelgen.generate_biomes_at_block for
-- a column of MapBlocks W in width and H in height, assuming that
-- TABLE's coordinates have been translated into Minecraft's
-- coordinate system.  Return a table of node metadata values indexed
-- by suitably inverted relative MapBlock positions.

local insert = table.insert

function mcl_levelgen.encode_biomes (biomes, w, h, hash_for_testing)
	local qw = w * N
	local qh = h * N
	local max_index = index (qw - 1, qh - 1, qw - 1, qw, qh, qw)
	assert (#biomes == max_index)
	local x_stride = qw * qh
	local y_stride = qw
	local compressed = {}

	for x = 0, w - 1 do
		for y = 0, h - 1 do
			for z = 0, w - 1 do
				local qx, qy, qz = x * N, y * N, (w - z) * N
				local base = index (qx, qy, qz, qw, qh, qw)
				local list = {}
				local n, biome = 0, nil

				for ix = 0, N - 1 do
					local ybase = base
					for iy = 0, N - 1 do
						for iz = 1, N do
							local b = biomes[base - iz]
							if b == biome or not biome then
								n = n + 1
							else
								insert (list, n)
								insert (list, biome)
								n = 1
							end
							biome = b
						end
						ybase = ybase + y_stride
					end
					base = base + x_stride
				end
				if biome ~= nil then
					insert (list, n)
					insert (list, biome)
				end
				if not hash_for_testing then
					compressed[{ x = x, y = y, z = z, }] = list
				else
					compressed[x * h * w + y * w + z + 1] = list
				end
			end
		end
	end
	return compressed
end

end

function mcl_levelgen.index_biome_list (list, qx, qy, qz)
	assert (qx < N and qy < N and qz < N)
	local i, idx = 1, qx * N * N + qy * N + qz + 1
	local biome
	repeat
		idx = idx - list[i]
		biome = list[i + 1]
		i = i + 2
	until idx <= 0
	return biome
end

if false then
	local seed = mcl_levelgen.ull (0, 3228473)
	local level = mcl_levelgen.make_overworld_preset (seed)
	local biomes = {}
	core = {}
	print ("Generating biomes...")
	for i = 0, 9 do
		local clock = os.clock ()
		mcl_levelgen.generate_biomes_at_block (level, biomes, 0, 0, 0, 5, 5)
		local fin = os.clock () - clock
		print (fin)
	end
	print ("Compressing biomes...")
	local compressed = mcl_levelgen.encode_biomes (biomes, 5, 5, true)
	print ("Testing biome compression routines...")
	local w, h = 5, 5
	for x = 0, 4 do
		for y = 0, 4 do
			for z = 0, 4 do
				local hash = x * h * w + y * w + z + 1
				local tbl = compressed[hash]
				local z_minecraft = 4 - z
				local qx, qy, qz = x * N, y * N, z_minecraft * N

				for x = 0, N - 1 do
					for y = 0, N - 1 do
						for z = 0, N - 1 do
							local qzd = qz + (N - z - 1)
							local i = index (qx + x, qy + y, qzd,
									 w * N, h * N, w * N)
							local a = mcl_levelgen.index_biome_list (tbl, x, y, z)
							local b = biomes[i]
							assert (a == b)
						end
					end
				end
			end
		end
	end
end

------------------------------------------------------------------------
-- Biome data storage.
------------------------------------------------------------------------

if core and core.get_meta then -- Mod environment.

local floor = math.floor
local fmod = math.fmod
local deserialize = core.deserialize
local serialize = core.serialize
local mod_storage = core.get_mod_storage ()
local v = vector.zero ()
local toquart = mcl_levelgen.toquart

function mcl_levelgen.get_biome (pos)
	local bx, by, bz
	bx = floor (pos.x / 16)
	by = floor (pos.y / 16)
	bz = floor (pos.z / 16)

	-- Do not attempt this if the engine might block to obtain
	-- metadata for this node.
	v.x = bx * 16
	v.y = by * 16
	v.z = bz * 16
	if not core.get_node_or_nil (v) then
		return nil
	end

	local meta = core.get_meta (v)
	local str = meta:get_string ("mcl_levelgen:biome_index")
	if not str or str == "" then
		-- Biome index was overwritten; load it from mod
		-- storage.
		str = mod_storage:get_string (table.concat ({
			tostring (bx), ",",
			tostring (by), ",",
			tostring (bz),
		}))

		if not str or str == "" then
			return nil
		end
		meta:set_string ("mcl_levelgen:biome_index", str)
	end

	local tbl = deserialize (str)
	local qx = toquart (floor (pos.x - v.x))
	local qy = toquart (floor (pos.y - v.y))
	local qz = toquart (floor (pos.z - v.z))
	return mcl_levelgen.index_biome_list (tbl, qx, qy, qz)
end

local function save_biome_index (pos, bx, by, bz, index)
	local str = serialize (index)
	local meta = core.get_meta (pos)
	meta:set_string ("mcl_levelgen:biome_index", str)
	mod_storage:set_string (table.concat ({
		tostring (bx), ",",
		tostring (by), ",",
		tostring (bz),
	}), str)
end

core.set_gen_notify ({ custom = true, }, nil, { "mcl_levelgen:biome_data", })

core.register_on_generated (function (minp, maxp, blockseed)
	local custom = core.get_mapgen_object ("gennotify").custom
	if not custom then
		return
	end
	local data = custom["mcl_levelgen:biome_data"]
	if not data then
		return
	end
	local x, y, z = minp.x, minp.y, minp.z
	local bx, by, bz = x / 16, y / 16, z / 16
	for pos, index in pairs (data) do
		local ix, iy, iz = pos.x, pos.y, pos.z
		pos.x = pos.x * 16 + x
		pos.y = pos.y * 16 + y
		pos.z = pos.z * 16 + z
		save_biome_index (pos, bx + ix, by + iy, bz + iz, index)
	end
end)

end
