name = mcl_levelgen
description = Minecraft-like asynchronous level generator
depends = mcl_init, mcl_util, mcl_worlds, mcl_player, mcl_liquids, mcl_mapgen_models
>>>>>>> 24c98ad0e (Adapt Lua liquid transformations to mcl_levelgen)
